export const users = [
  {
    id: 1,
    organization: 'TechCorp',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@techcorp.com',
    phoneNumber: '123-456-7890',
    dateJoined: '2023-01-15',
    status: 'Active',
  },
  {
    id: 2,
    organization: 'HealthPlus',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@healthplus.com',
    phoneNumber: '234-567-8901',
    dateJoined: '2022-05-21',
    status: 'Inactive',
  },
  {
    id: 3,
    organization: 'EduWorld',
    firstName: 'Alice',
    lastName: 'Johnson',
    email: 'alice.johnson@eduworld.com',
    phoneNumber: '345-678-9012',
    dateJoined: '2024-03-12',
    status: 'Active',
  },
  {
    id: 4,
    organization: 'FinanceGroup',
    firstName: 'Bob',
    lastName: 'Brown',
    email: 'bob.brown@financegroup.com',
    phoneNumber: '456-789-0123',
    dateJoined: '2021-08-30',
    status: 'Pending',
  },
  {
    id: 5,
    organization: 'TechCorp',
    firstName: 'Charlie',
    lastName: 'Davis',
    email: 'charlie.davis@techcorp.com',
    phoneNumber: '567-890-1234',
    dateJoined: '2020-11-05',
    status: 'Blacklisted',
  },
  {
    id: 6,
    organization: 'HealthPlus',
    firstName: 'Diana',
    lastName: 'Miller',
    email: 'diana.miller@healthplus.com',
    phoneNumber: '678-901-2345',
    dateJoined: '2022-07-19',
    status: 'Inactive',
  },
  {
    id: 7,
    organization: 'EduWorld',
    firstName: 'Edward',
    lastName: 'Wilson',
    email: 'edward.wilson@eduworld.com',
    phoneNumber: '789-012-3456',
    dateJoined: '2023-02-23',
    status: 'Pending',
  },
  {
    id: 8,
    organization: 'FinanceGroup',
    firstName: 'Fiona',
    lastName: 'Moore',
    email: 'fiona.moore@financegroup.com',
    phoneNumber: '890-123-4567',
    dateJoined: '2021-06-11',
    status: 'Active',
  },
  {
    id: 9,
    organization: 'TechCorp',
    firstName: 'George',
    lastName: 'Taylor',
    email: 'george.taylor@techcorp.com',
    phoneNumber: '901-234-5678',
    dateJoined: '2020-09-22',
    status: 'Inactive',
  },
  {
    id: 10,
    organization: 'HealthPlus',
    firstName: 'Hannah',
    lastName: 'Anderson',
    email: 'hannah.anderson@healthplus.com',
    phoneNumber: '012-345-6789',
    dateJoined: '2022-04-17',
    status: 'Active',
  },
  {
    id: 11,
    organization: 'EduWorld',
    firstName: 'Ian',
    lastName: 'Thomas',
    email: 'ian.thomas@eduworld.com',
    phoneNumber: '123-456-7890',
    dateJoined: '2023-10-10',
    status: 'Pending',
  },
  {
    id: 12,
    organization: 'FinanceGroup',
    firstName: 'Julia',
    lastName: 'Jackson',
    email: 'julia.jackson@financegroup.com',
    phoneNumber: '234-567-8901',
    dateJoined: '2021-12-29',
    status: 'Active',
  },
  {
    id: 13,
    organization: 'TechCorp',
    firstName: 'Kevin',
    lastName: 'White',
    email: 'kevin.white@techcorp.com',
    phoneNumber: '345-678-9012',
    dateJoined: '2020-03-03',
    status: 'Blacklisted',
  },
  {
    id: 14,
    organization: 'HealthPlus',
    firstName: 'Laura',
    lastName: 'Harris',
    email: 'laura.harris@healthplus.com',
    phoneNumber: '456-789-0123',
    dateJoined: '2022-09-25',
    status: 'Pending',
  },
  {
    id: 15,
    organization: 'EduWorld',
    firstName: 'Michael',
    lastName: 'Martin',
    email: 'michael.martin@eduworld.com',
    phoneNumber: '567-890-1234',
    dateJoined: '2024-01-20',
    status: 'Active',
  },
  {
    id: 16,
    organization: 'FinanceGroup',
    firstName: 'Nancy',
    lastName: 'Thompson',
    email: 'nancy.thompson@financegroup.com',
    phoneNumber: '678-901-2345',
    dateJoined: '2021-11-04',
    status: 'Inactive',
  },
  {
    id: 17,
    organization: 'TechCorp',
    firstName: 'Oliver',
    lastName: 'Garcia',
    email: 'oliver.garcia@techcorp.com',
    phoneNumber: '789-012-3456',
    dateJoined: '2020-05-13',
    status: 'Active',
  },
  {
    id: 18,
    organization: 'HealthPlus',
    firstName: 'Pamela',
    lastName: 'Martinez',
    email: 'pamela.martinez@healthplus.com',
    phoneNumber: '890-123-4567',
    dateJoined: '2022-08-14',
    status: 'Pending',
  },
  {
    id: 19,
    organization: 'EduWorld',
    firstName: 'Quentin',
    lastName: 'Robinson',
    email: 'quentin.robinson@eduworld.com',
    phoneNumber: '901-234-5678',
    dateJoined: '2023-06-18',
    status: 'Blacklisted',
  },
  {
    id: 20,
    organization: 'FinanceGroup',
    firstName: 'Rachel',
    lastName: 'Clark',
    email: 'rachel.clark@financegroup.com',
    phoneNumber: '012-345-6789',
    dateJoined: '2021-07-27',
    status: 'Inactive',
  },
  {
    id: 21,
    organization: 'TechCorp',
    firstName: 'Sam',
    lastName: 'Young',
    email: 'sam.young@techcorp.com',
    phoneNumber: '123-456-7890',
    dateJoined: '2023-04-01',
    status: 'Pending',
  },
  {
    id: 22,
    organization: 'HealthPlus',
    firstName: 'Tina',
    lastName: 'Hill',
    email: 'tina.hill@healthplus.com',
    phoneNumber: '234-567-8901',
    dateJoined: '2022-03-06',
    status: 'Active',
  },
  {
    id: 23,
    organization: 'EduWorld',
    firstName: 'Uma',
    lastName: 'Scott',
    email: 'uma.scott@eduworld.com',
    phoneNumber: '345-678-9012',
    dateJoined: '2024-02-15',
    status: 'Inactive',
  },
  {
    id: 24,
    organization: 'FinanceGroup',
    firstName: 'Victor',
    lastName: 'Green',
    email: 'victor.green@financegroup.com',
    phoneNumber: '456-789-0123',
    dateJoined: '2021-10-22',
    status: 'Blacklisted',
  },
  {
    id: 25,
    organization: 'TechCorp',
    firstName: 'Wendy',
    lastName: 'King',
    email: 'wendy.king@techcorp.com',
    phoneNumber: '567-890-1234',
    dateJoined: '2020-12-15',
    status: 'Active',
  },
  {
    id: 26,
    organization: 'HealthPlus',
    firstName: 'Xander',
    lastName: 'Lee',
    email: 'xander.lee@healthplus.com',
    phoneNumber: '678-901-2345',
    dateJoined: '2022-01-09',
    status: 'Inactive',
  },
  {
    id: 27,
    organization: 'EduWorld',
    firstName: 'Yvonne',
    lastName: 'Walker',
    email: 'yvonne.walker@eduworld.com',
    phoneNumber: '789-012-3456',
    dateJoined: '2023-07-13',
    status: 'Pending',
  },
  {
    id: 28,
    organization: 'TechCorp',
    firstName: 'Emily',
    lastName: 'Clark',
    email: 'emily.clark@techcorp.com',
    phoneNumber: '321-654-0987',
    dateJoined: '2024-06-01',
    status: 'Active',
  },
  {
    id: 29,
    organization: 'HealthPlus',
    firstName: 'David',
    lastName: 'Evans',
    email: 'david.evans@healthplus.com',
    phoneNumber: '432-765-1098',
    dateJoined: '2023-07-15',
    status: 'Blacklisted',
  },
  {
    id: 30,
    organization: 'EduWorld',
    firstName: 'Sophia',
    lastName: 'Garcia',
    email: 'sophia.garcia@eduworld.com',
    phoneNumber: '543-876-2109',
    dateJoined: '2022-08-20',
    status: 'Pending',
  },
];